---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: faf837f69f8f2465d33da36354ac1f54cd019b27
    app.quarkus.io/build-timestamp: 2022-05-01 - 07:58:33 +0000
  labels:
    app.kubernetes.io/name: rest-social-number
    app.kubernetes.io/version: latest
  name: rest-social-number
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8081
  selector:
    app.kubernetes.io/name: rest-social-number
    app.kubernetes.io/version: latest
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: faf837f69f8f2465d33da36354ac1f54cd019b27
    app.quarkus.io/build-timestamp: 2022-05-01 - 07:58:33 +0000
  labels:
    app.kubernetes.io/version: latest
    app.kubernetes.io/name: rest-social-number
  name: rest-social-number
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: latest
      app.kubernetes.io/name: rest-social-number
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: faf837f69f8f2465d33da36354ac1f54cd019b27
        app.quarkus.io/build-timestamp: 2022-05-01 - 07:58:33 +0000
      labels:
        app.kubernetes.io/version: latest
        app.kubernetes.io/name: rest-social-number
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: registry.hub.docker.com/hoangnguyent/rest-social-number:latest
          imagePullPolicy: IfNotPresent
          name: rest-social-number
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
